[colors.bright]
black = "0xb0b0b0"
blue = "0x3777e6"
cyan = "0x1faaaa"
green = "0x00c918"
magenta = "0xad00a1"
red = "0xff0086"
white = "0x101010"
yellow = "0xaba800"

[colors.normal]
black = "0xffffff"
blue = "0x3777e6"
cyan = "0x1faaaa"
green = "0x00c918"
magenta = "0xad00a1"
red = "0xff0086"
white = "0x101010"
yellow = "0xaba800"

[colors.primary]
background = "0xffffff"
foreground = "0x101010"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[general]
live_config_reload = true

[window]
decorations = "None"
startup_mode = "Maximized"
