#!/bin/sh

bspc config click_to_focus button1
bspc config split_ratio    0.52
bspc config window_gap     0

bspc config borderless_monocle   true
bspc config gapless_monocle      true
for side in top right bottom left; do
    bspc config ${side}_monocle_padding -$(bspc config ${side}_padding)
done

bspc config active_border_color    "#ff0000"
bspc config focused_border_color   "#ffa500"
bspc config normal_border_color    "#332d29"
bspc config presel_feedback_color  "#9a875f"

bspc rule -a Conky          sticky=on  manage=off lower=on
bspc rule -a Emacs          state=tiled
bspc rule -a pinentry-gtk-2 follow=off state=floating
bspc rule -a VirtualBox     state=floating

. ~/.config/bspwm/bspwmrc.local
